services:
  - type: web
    name: smtp-server
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        fromService:
          type: web
          name: smtp-server
          envVarKey: PORT
      - key: SMTP_PORT
        value: 2525